name: Compile Assets

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  compile-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Compile Assets
        run: npm run build

      - name: Deploy compiled assets
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build assets
          push_options: '--force'